# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in my_gem.gemspec
gemspec

gem 'irb'
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.12' # Hoặc phiên bản mới nhất
